---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "openshiftUserAuthTracker.name" . }}
  labels:
    {{- include "openshiftUserAuthTracker.labels" . | nindent 4 }}
rules:
- apiGroups:
  - oauth.openshift.io
  resources:
  - oauthaccesstokens
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - user.openshift.io
  resources:
  - users
  verbs:
  - get
  - patch
- apiGroups:
  - ""
  attributeRestrictions: null
  resources:
  - events
  verbs:
  - create
  - patch
  - update
