{{- if .Values.namespace.create -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "openshiftUserAuthTracker.namespaceName" . }}
  labels:
    {{- include "openshiftUserAuthTracker.labels" . | nindent 4 }}
{{- end -}}
